name: Surge Action
on:
   push:
     branches: [ main ]
jobs:
  build:

     runs-on: ubuntu_latest
   
  steps:
   
   - uses: actions/checkout@v2
   - uses: actions/cache@v3.0.11
   - uses: actions/setup-node@v2
   
     with:
       node-version: 12
   
   - name: check commands
     run: pwd
      
    - name: checking up the list
      run : npm install -g surge
      
    - name: Deploy the website
      run: surge ./ magical-word.surge.sh--token${{secrets.TESTING_SURGE_TOKEN}}
